### ISSUE TITLE
Minor changes to rendered graphics via different versions or implementations of ImageMagick

### ISSUE THREAD

**Issue by jraller** [freelawproject/seal-rookery#4]
I used ImageMagick 6.9.0 Q16 to process some new and changed orig files, and it altered files by 3 to 4 bytes that should not have been changed.

Potential options:

 - .gitignore the rendered folders, but that doesn't allow this repository to hold all four sizes.
 - alter convert_images.py to only generate files altered after a certain date.
 - determine what the 3 or 4 byte difference is and normalize for it.

**Comment by mlissner** [comment]
This is improved enough in the current push that I'm calling it fixed. The fix is pretty simple: For every seal in the rookery, I added a sha2 hash to `seals.json`. When the `convert_images.py` script is run it checks these values and only regenerates images if their hash has changed. Git stores these values too, but I figured it's easier to generate and store them ourselves than to interface with git, have the dependency on that, etc.

I expect that this will cause a headache at some point because it can't be turned off via a command arg, but that's a task for another day. The current fix is good enough that this issue is resolved and we can deal with more complexity later, if it's needed. (I also suspect that in the future we'll be able to just hack the script temporarily if we need to bypass the hash check or whatever.)
